# Generated by Django 4.1.5 on 2023-01-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_address_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='address',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
            preserve_default=False,
        ),
    ]
