# Generated by Django 4.1.5 on 2023-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
