# Generated by Django 4.1.5 on 2023-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wholesale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='slug',
            field=models.SlugField(),
        ),
    ]
