# Generated by Django 4.1.6 on 2023-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_wholesale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='image',
            field=models.ImageField(upload_to='wholesale'),
        ),
    ]
